"""Generated shell scripts and submission guide for a package.

Scripts are written with LF line endings and are deterministic for a given
package. Every configurable value is a validated structured field and is
inserted with shell quoting; Slurm directives only carry values that the
profile model restricts to letters, digits and a few separators.
"""

from __future__ import annotations

import shlex
from pathlib import Path

from cellquant.__version__ import __version__
from cellquant.hpc.models import BundleManifest, ClusterProfile, RuntimeContract

# Slurm sends SIGUSR1 to the batch shell this many seconds before the time limit,
# so the worker stops starting new images and publishes what is finished.
SIGNAL_SECONDS = 600


def walltime(seconds: int) -> str:
    days, rest = divmod(int(seconds), 86400)
    hours, rest = divmod(rest, 3600)
    minutes, secs = divmod(rest, 60)
    clock = f"{hours:02d}:{minutes:02d}:{secs:02d}"
    return f"{days}-{clock}" if days else clock


def remote_package_dir(profile: ClusterProfile, manifest: BundleManifest) -> str:
    return f"{profile.remote_durable_root}/{manifest.package_name}"


def remote_results_root(profile: ClusterProfile, manifest: BundleManifest) -> str:
    return f"{profile.remote_durable_root}/results/{manifest.package_name}"


def _q(value: str) -> str:
    return shlex.quote(str(value))


def _header(manifest: BundleManifest, purpose: str) -> str:
    return (
        "#!/usr/bin/env bash\n"
        f"# {purpose}\n"
        f"# Generated by CellQuant {__version__} for package {manifest.package_name} (bundle {manifest.bundle_id}).\n"
        "# Do not edit: its checksum is part of the package. Prepare a new package to change anything.\n"
    )


def _module_lines(profile: ClusterProfile) -> str:
    if not profile.modules:
        return ""
    lines = ["if command -v module >/dev/null 2>&1; then"]
    lines += [f"  module load {_q(name)}" for name in profile.modules]
    lines += ["fi"]
    return "\n".join(lines) + "\n"


def _environment(runtime: RuntimeContract) -> str:
    return (
        f"export CELLPOSE_LOCAL_MODELS_PATH={_q(runtime.model_directory)}\n"
        "# Jobs never download software or model weights.\n"
        "export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 PIP_NO_INDEX=1\n"
        "export PYTHONNOUSERSITE=1 PYTHONDONTWRITEBYTECODE=1 MPLBACKEND=Agg QT_QPA_PLATFORM=offscreen\n"
    )


def submit_script(manifest: BundleManifest, profile: ClusterProfile, runtime: RuntimeContract) -> str:
    results_root = remote_results_root(profile, manifest)
    return (
        _header(manifest, "Check the package, create its results folder, and queue the GPU job.")
        + f"""set -euo pipefail
PKG="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd -P)"
PY={_q(profile.python_path)}
RESULTS_ROOT={_q(results_root)}
RESUME=""

usage() {{
  echo "Usage: bash scripts/submit.sh [--resume RUN_ID]"
  echo "  Without --resume, a new run is created under $RESULTS_ROOT."
  echo "  --resume RUN_ID continues that run: finished images are kept, the rest are run again."
}}
while [[ $# -gt 0 ]]; do
  case "$1" in
    --resume) RESUME="${{2:-}}"; [[ -n "$RESUME" ]] || {{ usage >&2; exit 2; }}; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if ! command -v sbatch >/dev/null 2>&1; then
  echo "sbatch was not found. Run this script on a cluster login node." >&2
  exit 2
fi
if [[ ! -x "$PY" ]]; then
  echo "The CellQuant Python environment was not found at $PY." >&2
  echo "Ask the maintainer for the environment named in the profile (runtime {runtime.runtime_id})." >&2
  exit 3
fi
{_module_lines(profile)}{_environment(runtime)}
echo "Checking the package (every file against its checksum)..."
"$PY" -m cellquant.hpc validate --bundle "$PKG"

ALLOCATE=(allocate --bundle "$PKG" --results "$RESULTS_ROOT" --shell)
if [[ -n "$RESUME" ]]; then ALLOCATE+=(--resume "$RESUME"); fi
ALLOCATION="$("$PY" -m cellquant.hpc "${{ALLOCATE[@]}}")"
eval "$ALLOCATION"   # sets RUN_ID ATTEMPT_ID RUN_DIR LOG_DIR (quoted by CellQuant)

JOB_ARGS=("$PKG" "$RUN_DIR" "$ATTEMPT_ID")
if [[ -n "$RESUME" ]]; then JOB_ARGS+=(--resume); fi
SUBMITTED="$(sbatch --parsable --job-name=cq_{manifest.package_name[7:]} \\
  --output="$LOG_DIR/slurm-%j.out" --error="$LOG_DIR/slurm-%j.out" \\
  "$PKG/scripts/job.sbatch" "${{JOB_ARGS[@]}}")"
JOB_ID="${{SUBMITTED%%;*}}"
"$PY" -m cellquant.hpc record-job --run-dir "$RUN_DIR" --attempt-id "$ATTEMPT_ID" --job-id "$JOB_ID" >/dev/null

echo
echo "Submitted job $JOB_ID (run $RUN_ID, attempt $ATTEMPT_ID)."
echo "  Watch the queue:   squeue -j $JOB_ID"
echo "  After it ends:     sacct -j $JOB_ID --format=JobID,State,Elapsed,ExitCode"
echo "  Job log:           $LOG_DIR/slurm-$JOB_ID.out"
echo "  Results:           $RUN_DIR (results.json lists every image)"
echo "  To continue later: bash scripts/submit.sh --resume $RUN_ID"
"""
    )


def job_script(manifest: BundleManifest, profile: ClusterProfile, runtime: RuntimeContract) -> str:
    directives = [
        f"#SBATCH --account={profile.account}",
        f"#SBATCH --partition={profile.partition}",
        *( [f"#SBATCH --qos={profile.qos}"] if profile.qos else [] ),
        f"#SBATCH --gres={profile.gpu_resource}",
        "#SBATCH --nodes=1",
        "#SBATCH --ntasks=1",
        f"#SBATCH --cpus-per-task={profile.cpus}",
        f"#SBATCH --mem={profile.memory_mib}M",
        f"#SBATCH --time={walltime(profile.walltime_seconds)}",
        f"#SBATCH --signal=B:USR1@{min(SIGNAL_SECONDS, max(60, profile.walltime_seconds // 4))}",
    ]
    scratch = f"{profile.scratch_root}/{manifest.package_name}"
    return (
        _header(manifest, "The GPU job: check the node, copy the package to scratch, analyze, publish results.")
        + "\n".join(directives)
        + f"""
set -uo pipefail
if [[ $# -lt 3 ]]; then
  echo "Submit this job with scripts/submit.sh, not sbatch directly." >&2
  exit 2
fi
PKG="$1"; RUN_DIR="$2"; ATTEMPT_ID="$3"; shift 3
EXTRA=("$@")
PY={_q(profile.python_path)}
RUN_ID="$(basename "$RUN_DIR")"
WORK={_q(scratch)}/"$RUN_ID/$ATTEMPT_ID"
ATTEMPT_DIR="$RUN_DIR/attempts/$ATTEMPT_ID"
{_module_lines(profile)}{_environment(runtime)}export OMP_NUM_THREADS="${{SLURM_CPUS_PER_TASK:-1}}"

echo "CellQuant job ${{SLURM_JOB_ID:-?}} on $(hostname) at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "Package: $PKG"
echo "Run:     $RUN_DIR (attempt $ATTEMPT_ID)"
echo "Scratch: $WORK"

echo "Checking this node: GPU, software and model weights..."
STATUS=0
"$PY" -m cellquant.hpc preflight --bundle "$PKG" --require-gpu --output "$ATTEMPT_DIR/preflight.json" || STATUS=$?
if [[ "$STATUS" != 0 ]]; then
  echo "The node check failed; nothing was analyzed. See $ATTEMPT_DIR/preflight.json" >&2
  "$PY" -m cellquant.hpc mark-attempt --run-dir "$RUN_DIR" --attempt-id "$ATTEMPT_ID" --note "preflight failed with exit code $STATUS" || true
  exit "$STATUS"
fi

mkdir -p "$WORK"
echo "Copying the package to scratch..."
if ! cp -R "$PKG" "$WORK/package"; then
  echo "Copying to scratch failed. Nothing was analyzed." >&2
  "$PY" -m cellquant.hpc mark-attempt --run-dir "$RUN_DIR" --attempt-id "$ATTEMPT_ID" --note "copy to scratch failed" || true
  exit 5
fi

"$PY" -m cellquant.hpc run --bundle "$WORK/package" --scratch-results "$WORK/results" \\
  --publish-to "$RUN_DIR" --attempt-id "$ATTEMPT_ID" ${{EXTRA[@]+"${{EXTRA[@]}}"}} &
CHILD=$!
# Slurm's early warning (USR1) and scancel (TERM) are passed to the worker, which stops
# starting new images and keeps only fully verified results.
trap 'kill -USR1 "$CHILD" 2>/dev/null' USR1
trap 'kill -TERM "$CHILD" 2>/dev/null' TERM INT
STATUS=0
while true; do
  wait "$CHILD"
  STATUS=$?
  if ! kill -0 "$CHILD" 2>/dev/null; then break; fi
done

echo "Worker finished with exit code $STATUS at $(date -u +%Y-%m-%dT%H:%M:%SZ)."
echo "Results: $RUN_DIR/results.json"
echo "Scratch was kept: $WORK"
echo "After you have checked and downloaded the results, remove it with:  rm -rf -- '$WORK'"
exit "$STATUS"
"""
    )


def preflight_script(manifest: BundleManifest, profile: ClusterProfile, runtime: RuntimeContract) -> str:
    return (
        _header(manifest, "Check the package and the cluster environment before submitting.")
        + f"""set -euo pipefail
PKG="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd -P)"
PY={_q(profile.python_path)}
ON_GPU=0
for argument in "$@"; do
  case "$argument" in
    --on-gpu) ON_GPU=1 ;;
    -h|--help)
      echo "Usage: bash scripts/preflight.sh [--on-gpu]"
      echo "  Without options: checks the package, the software and the model files here (no GPU work)."
      echo "  --on-gpu: also runs a small segmentation on a GPU node for up to 15 minutes (uses your allocation)."
      exit 0 ;;
    *) echo "Unknown argument: $argument" >&2; exit 2 ;;
  esac
done
if [[ ! -x "$PY" ]]; then
  echo "The CellQuant Python environment was not found at $PY." >&2
  exit 3
fi
{_module_lines(profile)}{_environment(runtime)}
"$PY" -m cellquant.hpc validate --bundle "$PKG"
"$PY" -m cellquant.hpc preflight --bundle "$PKG" --output -
if [[ "$ON_GPU" == 1 ]]; then
  echo "Asking for a GPU for up to 15 minutes to test a small segmentation..."
  srun --account={profile.account} --partition={profile.partition} {"--qos=" + profile.qos if profile.qos else ""} \\
    --gres={profile.gpu_resource} --nodes=1 --ntasks=1 --cpus-per-task={min(profile.cpus, 4)} --mem=16G --time=00:15:00 \\
    "$PY" -m cellquant.hpc preflight --bundle "$PKG" --require-gpu --output -
fi
echo "Preflight passed. Submit with: bash scripts/submit.sh"
"""
    )


def readme(manifest: BundleManifest, profile: ClusterProfile, runtime: RuntimeContract, *, local_package: str = "") -> str:
    package_remote = remote_package_dir(profile, manifest)
    results_root = remote_results_root(profile, manifest)
    count = len(manifest.acquisitions)
    status = (
        f"production-verified (smoke test {profile.live_smoke_date})"
        if profile.validation_status == "production" and profile.live_smoke_date
        else "experimental: no cluster smoke test is recorded for this profile"
    )
    local = local_package or "<this package on your computer>"
    return f"""# Submitting {manifest.package_name}

{count} image{'s' if count != 1 else ''} from experiment "{manifest.source_experiment_name}", prepared {manifest.created_at} by CellQuant {manifest.cellquant_version}.
Engine {runtime.engine} {runtime.cellpose_version}, model `{runtime.model}`, Z mode `{', '.join(sorted({item.effective_z_mode for item in manifest.acquisitions}))}`.
Profile `{profile.profile_id}` ({status}); runtime `{runtime.runtime_id}`.

Do not rename or edit anything inside this folder. Every file is checksummed; a changed file stops the job
before any analysis. To change settings or resources, prepare a new package in CellQuant.

## 1. Transfer

Copy the whole folder so that it ends up at:

    {package_remote}

For large packages use Globus. From a terminal on your computer, rsync also works (replace YOUR_USERNAME):

    rsync -av --partial "{local}" YOUR_USERNAME@{profile.host}:{_q(profile.remote_durable_root + "/")}

## 2. Check, then submit (on a login node)

    cd {_q(package_remote)}
    bash scripts/preflight.sh            # package, software and model files; no GPU work
    bash scripts/preflight.sh --on-gpu   # optional: a small segmentation on a GPU node
    bash scripts/submit.sh

`submit.sh` checks every file again, creates the run folder and its log folder, queues one job
({profile.gpu_resource}, {profile.cpus} CPUs, {profile.memory_mib} MiB, time limit {walltime(profile.walltime_seconds)}),
and prints the job ID, the log file and the results folder.

## 3. While it runs

    squeue -j JOB_ID
    tail -f {results_root}/RUN_ID/attempts/ATTEMPT_ID/logs/slurm-JOB_ID.out
    scancel JOB_ID      # stops after the current image; finished images are kept

The job first checks the GPU node (preflight). It never falls back to the CPU and never downloads models.
Images are analyzed one at a time, and each finished image is published to the results folder before the next
starts. Working copies live in scratch under {profile.scratch_root}/{manifest.package_name}/ and are kept; the
job log prints the exact folder and the command to remove it once you have your results.

## 4. If the job stopped early

- Timed out or cancelled: `bash scripts/submit.sh --resume RUN_ID`. Finished images are checked and kept;
  the rest run again.
- If submit.sh says the run is still owned by an earlier job, first make sure that job is no longer running
  (`sacct -j JOB_ID`), then run the `recover-lease` command it prints. CellQuant refuses to recover while
  Slurm reports the job as pending, running or requeued, or cannot say.

## 5. Bring the results back

Download the whole run folder `{results_root}/RUN_ID` (it contains `results.json`, `tasks/` and `attempts/`).
In CellQuant: Start tab, **HPC prep**, **6. Import results**. Choose this package (the copy on your computer),
the downloaded run folder, and a new empty folder for the imported experiment. Or, in a terminal with the
CellQuant environment active:

    python -m cellquant.hpc import --bundle "{local}" --results "<downloaded run folder>" --destination "<new folder>"

The import creates a new experiment with its own copy of the images; your original experiment is not changed.
Manual edits and approvals from the original experiment are not applied to the new segmentation.
"""


def write_scripts(root: Path, manifest: BundleManifest, profile: ClusterProfile, runtime: RuntimeContract, *, local_package: str = "") -> list[str]:
    from cellquant.hpc.common import write_text_lf

    files = {
        "scripts/submit.sh": (submit_script(manifest, profile, runtime), True),
        "scripts/job.sbatch": (job_script(manifest, profile, runtime), True),
        "scripts/preflight.sh": (preflight_script(manifest, profile, runtime), True),
        "README_SUBMIT.md": (readme(manifest, profile, runtime, local_package=local_package), False),
    }
    for relative, (text, executable) in files.items():
        write_text_lf(root / relative, text, executable=executable)
    return list(files)
